<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<form class="form form-orders-search"
      id="oar-widget-orders-and-returns-form"
      data-mage-init='{"ordersReturns":{}, "validation":{}}'
      action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
      method="post" name="guest_post">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Order Information')) ?></span></legend>
        <br>

        <div class="field id required">
            <label class="label" for="oar-order-id"><span><?= $block->escapeHtml(__('Order ID')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field password required">
            <label class="label" for="oar-billing-password"><span><?= $block->escapeHtml(__('Password')) ?></span></label>

            <div class="control">
                <input type="password" class="input-text" id="oar-billing-password" name="oar_billing_password"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div id="oar-zip" style="display: none;" class="field zip required">
            <label class="label" for="oar_zip"><span><?= $block->escapeHtml(__('Billing ZIP Code')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>
    </div>
</form>